name: art_reference_app
description: "An app for collecting and organizing art reference images."
publish_to: 'none'

version: 1.2.0+69
environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^6.0.1
  uuid: ^4.6.0
  image: ^4.5.4
  platform_image_converter: ^2.1.3
  cryptography: ^2.9.0
  share_plus: ^13.3.0
  http: ^1.6.0
  gal: ^2.3.3
  printing: ^5.15.0
  pdf: ^3.13.0
  receive_sharing_intent: ^1.9.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.6
  file_selector: ^1.1.0
  device_info_plus: ^13.2.0
  url_launcher: ^6.3.2
  crypto: ^3.0.7

dev_dependencies:
  supabase: ^2.14.0

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/category_thumbnails/
    - assets/help/
    - assets/app_icon.png
    - env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  remove_alpha_ios: true

  web:
    generate: true
    image_path: assets/app_icon.png
    background_color: "#211638"
    theme_color: "#211638"

  windows:
    generate: true
    image_path: assets/app_icon.png
    icon_size: 256
