


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."image_assets" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "date_added" timestamp with time zone DEFAULT "now"() NOT NULL,
    "width" integer,
    "height" integer,
    "user_email" "text",
    "image_hash" "text",
    "storage_path" "text",
    "thumbnail_storage_path" "text",
    "title" "text",
    "notes" "text",
    "source_url" "text",
    "is_favorite" boolean DEFAULT false NOT NULL,
    "ai_title" "text",
    "ai_description" "text",
    "ai_keywords" "text"[] DEFAULT '{}'::"text"[],
    "ai_subject_type" "text",
    "ai_lighting" "text",
    "ai_composition" "text",
    "ai_dominant_colors" "text"[] DEFAULT '{}'::"text"[],
    "ai_art_notes" "text",
    "ai_analysis_status" "text" DEFAULT 'not_analyzed'::"text",
    "ai_analyzed_at" timestamp with time zone,
    "ai_analysis_error" "text"
);


ALTER TABLE "public"."image_assets" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."image_categories" (
    "image_id" "uuid" NOT NULL,
    "category_code" "text" NOT NULL,
    "date_added" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."image_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."image_keywords" (
    "id" bigint NOT NULL,
    "user_id" "text" NOT NULL,
    "image_id" "uuid" NOT NULL,
    "keyword" "text" NOT NULL,
    "date_added" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "image_keywords_keyword_length" CHECK (("length"(TRIM(BOTH FROM "keyword")) <= 100)),
    CONSTRAINT "image_keywords_keyword_not_empty" CHECK (("length"(TRIM(BOTH FROM "keyword")) > 0))
);


ALTER TABLE "public"."image_keywords" OWNER TO "postgres";


ALTER TABLE "public"."image_keywords" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."image_keywords_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."image_relationships" (
    "parent_image_id" "uuid" NOT NULL,
    "child_image_id" "uuid" NOT NULL,
    "date_added" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "image_relationships_no_self_link" CHECK (("parent_image_id" <> "child_image_id"))
);


ALTER TABLE "public"."image_relationships" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."reference_categories" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "code" "text" NOT NULL,
    "display_name" "text" NOT NULL,
    "thumbnail_asset" "text",
    "is_builtin" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "reference_categories_builtin_owner_check" CHECK (((("is_builtin" = true) AND ("user_id" IS NULL)) OR (("is_builtin" = false) AND ("user_id" IS NOT NULL)))),
    CONSTRAINT "reference_categories_code_not_empty" CHECK (("length"(TRIM(BOTH FROM "code")) > 0)),
    CONSTRAINT "reference_categories_name_not_empty" CHECK (("length"(TRIM(BOTH FROM "display_name")) > 0))
);


ALTER TABLE "public"."reference_categories" OWNER TO "postgres";


ALTER TABLE "public"."reference_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reference_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."image_categories"
    ADD CONSTRAINT "image_asset_categories_pkey" PRIMARY KEY ("image_id", "category_code");



ALTER TABLE ONLY "public"."image_assets"
    ADD CONSTRAINT "image_assets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."image_keywords"
    ADD CONSTRAINT "image_keywords_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."image_relationships"
    ADD CONSTRAINT "image_relationships_pkey" PRIMARY KEY ("parent_image_id", "child_image_id");



ALTER TABLE ONLY "public"."reference_categories"
    ADD CONSTRAINT "reference_categories_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "image_assets_user_hash_unique" ON "public"."image_assets" USING "btree" ("user_id", "image_hash") WHERE ("image_hash" IS NOT NULL);



CREATE UNIQUE INDEX "image_categories_image_category_unique" ON "public"."image_categories" USING "btree" ("image_id", "category_code");



CREATE INDEX "image_keywords_image_id_index" ON "public"."image_keywords" USING "btree" ("image_id");



CREATE INDEX "image_keywords_search_index" ON "public"."image_keywords" USING "btree" ("user_id", "lower"(TRIM(BOTH FROM "keyword")));



CREATE UNIQUE INDEX "image_keywords_unique_keyword_per_image" ON "public"."image_keywords" USING "btree" ("user_id", "image_id", "lower"(TRIM(BOTH FROM "keyword")));



CREATE INDEX "image_keywords_user_id_index" ON "public"."image_keywords" USING "btree" ("user_id");



CREATE UNIQUE INDEX "reference_categories_builtin_code_unique" ON "public"."reference_categories" USING "btree" ("code") WHERE ("is_builtin" = true);



CREATE UNIQUE INDEX "reference_categories_user_code_unique" ON "public"."reference_categories" USING "btree" ("user_id", "code") WHERE ("is_builtin" = false);



CREATE UNIQUE INDEX "reference_categories_user_name_unique" ON "public"."reference_categories" USING "btree" ("user_id", "lower"(TRIM(BOTH FROM "display_name"))) WHERE ("is_builtin" = false);



ALTER TABLE ONLY "public"."image_categories"
    ADD CONSTRAINT "image_asset_categories_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "public"."image_assets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."image_keywords"
    ADD CONSTRAINT "image_keywords_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "public"."image_assets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."image_relationships"
    ADD CONSTRAINT "image_relationships_child_image_id_fkey" FOREIGN KEY ("child_image_id") REFERENCES "public"."image_assets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."image_relationships"
    ADD CONSTRAINT "image_relationships_parent_image_id_fkey" FOREIGN KEY ("parent_image_id") REFERENCES "public"."image_assets"("id") ON DELETE CASCADE;



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."image_assets" TO "anon";
GRANT ALL ON TABLE "public"."image_assets" TO "authenticated";
GRANT ALL ON TABLE "public"."image_assets" TO "service_role";



GRANT ALL ON TABLE "public"."image_categories" TO "anon";
GRANT ALL ON TABLE "public"."image_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."image_categories" TO "service_role";



GRANT ALL ON TABLE "public"."image_keywords" TO "anon";
GRANT ALL ON TABLE "public"."image_keywords" TO "authenticated";
GRANT ALL ON TABLE "public"."image_keywords" TO "service_role";



GRANT ALL ON SEQUENCE "public"."image_keywords_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."image_keywords_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."image_keywords_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."image_relationships" TO "anon";
GRANT ALL ON TABLE "public"."image_relationships" TO "authenticated";
GRANT ALL ON TABLE "public"."image_relationships" TO "service_role";



GRANT ALL ON TABLE "public"."reference_categories" TO "anon";
GRANT ALL ON TABLE "public"."reference_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."reference_categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reference_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reference_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reference_categories_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







