-- Keeps the rows that describe a deleted image, so the bytes in the backup can
-- become a visible image again.
--
-- R2 holds the file and nothing else. A delete removes the image_assets row and
-- cascades through categories, keywords and relationships, so restoring only the
-- object puts an invisible blob back into storage: the app looks for images via
-- rows, and there is no row to find. This archives what the file alone cannot
-- carry.
--
-- Deliberately kept in Postgres rather than written to R2 alongside the object.
-- This exists for the case the database is alive and one image was deleted by
-- mistake, which is the common one. Surviving the loss of the whole project is a
-- different problem needing a different mechanism, and pretending this solves it
-- would be worse than not having it.

create table if not exists public.deleted_row_archive (
  id bigint generated by default as identity primary key,
  deleted_at timestamptz not null default now(),
  table_name text not null,
  -- The image this row described. Every archived table reaches an image one way
  -- or another, so a restore can gather a whole deletion from one id.
  image_id uuid,
  -- Relationships name two images; the second is kept so a restore finds the
  -- link from either end.
  related_image_id uuid,
  -- Text rather than uuid: image_keywords stores a different kind of user
  -- identifier than image_assets does, and a cast would fail on one of them.
  user_id text,
  row_data jsonb not null
);

create index if not exists deleted_row_archive_image_idx
  on public.deleted_row_archive (image_id);

create index if not exists deleted_row_archive_related_idx
  on public.deleted_row_archive (related_image_id);

create index if not exists deleted_row_archive_deleted_at_idx
  on public.deleted_row_archive (deleted_at desc);

-- No policies: readable only by the service role. Deleted rows are still the
-- user's data, and an archive that anyone could read would be a way around
-- deletion rather than a way back from it.
alter table public.deleted_row_archive enable row level security;

comment on table public.deleted_row_archive is
  'Rows removed by a delete, kept so an accidentally deleted image can be put '
  'back. Nothing purges this yet; retention is still to be decided.';

create or replace function public.archive_deleted_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  data jsonb := to_jsonb(old);
  primary_column text := tg_argv[0];
  secondary_column text := case when tg_nargs > 1 then tg_argv[1] end;
begin
  insert into public.deleted_row_archive (
    table_name, image_id, related_image_id, user_id, row_data
  )
  values (
    tg_table_name,
    nullif(data ->> primary_column, '')::uuid,
    case
      when secondary_column is null then null
      else nullif(data ->> secondary_column, '')::uuid
    end,
    case when data ? 'user_id' then data ->> 'user_id' end,
    data
  );

  return old;
exception
  when others then
    -- A failure to archive must not stop someone deleting their own image, but
    -- it must not pass unnoticed either: the earlier version of the replication
    -- trigger raised a warning nobody read and reported success while doing
    -- nothing, so this is recorded where it will be seen.
    begin
      insert into public.backup_replication_failures (
        operation, storage_path, error_message
      )
      values (
        'ARCHIVE ' || tg_table_name,
        coalesce(data ->> primary_column, '(unknown)'),
        sqlerrm
      );
    exception
      when others then
        raise warning 'archive_deleted_row could not record failure: %', sqlerrm;
    end;

    return old;
end;
$$;

revoke all on function public.archive_deleted_row() from anon, authenticated;

-- Before, not after: image_assets cascades into the other three, and an after
-- trigger on the parent would fire once the children were already gone.
drop trigger if exists archive_image_asset_delete on public.image_assets;
create trigger archive_image_asset_delete
  before delete on public.image_assets
  for each row
  execute function public.archive_deleted_row('id');

drop trigger if exists archive_image_category_delete on public.image_categories;
create trigger archive_image_category_delete
  before delete on public.image_categories
  for each row
  execute function public.archive_deleted_row('image_id');

drop trigger if exists archive_image_keyword_delete on public.image_keywords;
create trigger archive_image_keyword_delete
  before delete on public.image_keywords
  for each row
  execute function public.archive_deleted_row('image_id');

drop trigger if exists archive_image_relationship_delete
  on public.image_relationships;
create trigger archive_image_relationship_delete
  before delete on public.image_relationships
  for each row
  execute function public.archive_deleted_row(
    'parent_image_id', 'child_image_id'
  );

-- Puts the rows back.
--
-- Scoped to one deletion rather than one row: deleting an image also deletes the
-- sketches derived from it, and restoring the parent alone would leave the
-- family broken. Every row of a single transaction shares now(), so the deletion
-- that removed this image is identifiable exactly, without guessing at a time
-- window.
--
-- The file must already be back in storage before this runs. Inserting the row
-- fires replication, which reads the object from storage to copy it to the
-- backup; with no file there, the restored row would be unprotected.
create or replace function public.restore_archived_image(p_image_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  event_at timestamptz;
  image_ids uuid[];
  restored_images int := 0;
  restored_children int := 0;
  archived record;
begin
  select deleted_at into event_at
  from public.deleted_row_archive
  where table_name = 'image_assets'
    and image_id = p_image_id
  order by deleted_at desc
  limit 1;

  if event_at is null then
    return jsonb_build_object(
      'restored', false,
      'reason', 'No archived image_assets row for that id'
    );
  end if;

  if exists (select 1 from public.image_assets where id = p_image_id) then
    return jsonb_build_object(
      'restored', false,
      'reason', 'That image already exists; nothing to restore'
    );
  end if;

  -- The image plus anything linked to it by a relationship removed in the same
  -- deletion. Bounded on purpose: an account deletion empties these tables in
  -- one transaction too, and restoring by timestamp alone would drag a whole
  -- account back from one image id.
  select array_agg(distinct id) into image_ids
  from (
    select p_image_id as id
    union
    select a.related_image_id
    from public.deleted_row_archive a
    where a.deleted_at = event_at
      and a.table_name = 'image_relationships'
      and a.image_id = p_image_id
      and a.related_image_id is not null
    union
    select a.image_id
    from public.deleted_row_archive a
    where a.deleted_at = event_at
      and a.table_name = 'image_relationships'
      and a.related_image_id = p_image_id
      and a.image_id is not null
  ) as family;

  for archived in
    select row_data
    from public.deleted_row_archive
    where deleted_at = event_at
      and table_name = 'image_assets'
      and image_id = any(image_ids)
  loop
    insert into public.image_assets
    select (jsonb_populate_record(null::public.image_assets, archived.row_data)).*
    on conflict (id) do nothing;

    restored_images := restored_images + 1;
  end loop;

  -- Children come second: every one of them has a foreign key onto an image
  -- that has to exist first.
  for archived in
    select table_name, row_data
    from public.deleted_row_archive
    where deleted_at = event_at
      and table_name in (
        'image_categories', 'image_keywords', 'image_relationships'
      )
      and (
        image_id = any(image_ids)
        or related_image_id = any(image_ids)
      )
  loop
    if archived.table_name = 'image_categories' then
      insert into public.image_categories
      select (jsonb_populate_record(
        null::public.image_categories, archived.row_data
      )).*
      on conflict do nothing;
    elsif archived.table_name = 'image_keywords' then
      insert into public.image_keywords
      select (jsonb_populate_record(
        null::public.image_keywords, archived.row_data
      )).*
      on conflict do nothing;
    else
      insert into public.image_relationships
      select (jsonb_populate_record(
        null::public.image_relationships, archived.row_data
      )).*
      on conflict do nothing;
    end if;

    restored_children := restored_children + 1;
  end loop;

  return jsonb_build_object(
    'restored', true,
    'deleted_at', event_at,
    'image_ids', to_jsonb(image_ids),
    'restored_images', restored_images,
    'restored_child_rows', restored_children
  );
end;
$$;

revoke all on function public.restore_archived_image(uuid) from anon, authenticated;
